WARNING:tensorflow:From /home/liuchang/metagenrl/utils.py:155: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /home/liuchang/metagenrl/tflog_utils.py:44: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

Traceback (most recent call last):
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/redis/connection.py", line 609, in _connect
    raise err
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/redis/connection.py", line 597, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ray_experiments.py", line 251, in <module>
    init_ray(parsed_args.redis_address)
  File "ray_experiments.py", line 191, in init_ray
    ray.init(redis_address=redis_address)
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/ray/worker.py", line 791, in init
    connect_only=True)
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/ray/node.py", line 111, in __init__
    redis_client.get("session_name"))
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/redis/client.py", line 875, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/redis/connection.py", line 1185, in get_connection
    connection.connect()
  File "/home/liuchang/python3.6/lib/python3.6/site-packages/redis/connection.py", line 557, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 192.168.2.230:6379. Connection refused.
